can_create_pages: 'yes'
can_edit_pages: 'yes'
can_approve_pages: 'yes'
can_see_advanced_menu: 'yes'
can_edit_templates: 'yes'
can_see_language_preview: 'yes'
can_see_country_preview: 'yes'
can_unpublish_pages: 'yes'
can_publish_pages: 'yes'
can_edit_settings: 'yes'
can_edit_all_modules_by_default: 'yes'
